### ISSUE TITLE
(1.14.4) Compatibility

### ISSUE THREAD

**Issue by DatrixTHLK** [Matixsss/Minecraft-Zmod#6]
Hi,

Would you be able to add compatibility for [Quark](https://www.curseforge.com/minecraft/mc-mods/quark) and [Underground Biomes](https://www.curseforge.com/minecraft/mc-mods/underground-biomes)? I'm not seeing mining increase in level any time I mine the different stone from their mods. If not, would I have to let Quark and Underground Biomes mod devs know about it?

**Comment by Matixsss** [comment]
Hi
So you have configs where you can add manualy ores etc (use -zblockinfo command to get block name). I created this mod with intention that people can add blocks from others mod by own :)

**Comment by DatrixTHLK** [comment]
I was unaware. Thanks for that, now I can do it on my own! :)

**Comment by DatrixTHLK** [comment]
Hi,

Just one question now that I think about it and I've tried using this command for a little while and got nowhere...How does one utilize or use the *zblockinfo command in minecraft itself? Do you have an example of how to setup a custom block within blockExpSettings.json file. Say for example I wanted to put in a custom modded stone block such as [Almost all the ores](https://www.curseforge.com/minecraft/mc-mods/almost-all-the-ores) Pyrite would it just be "pyrite" or would I need to add the modid before "pyrite" with a colon after the modid? I feel as if I should have figured this out already, but I'm not that quick on the draw. Any help would be appreciated!

**Comment by DatrixTHLK** [comment]
Strange but I'm still not getting any xp from mining any modded blocks 
[ZModconfigs.zip](https://github.com/Matixsss/Minecraft-Zmod/files/3964579/ZModconfigs.zip)

Let me know if I'm doing something wrong here.

**Comment by Matixsss** [comment]
Ok i looked and you make some mistakes forget "," etc. In newest mod version i changed how config looks so its now easier to add things. If you want better looking configs just delete old one and newer will be generated.

I repaired your blockexpsettings :) but in the future i will not not do that kind of things :)

[BlockExpSettings.zip](https://github.com/Matixsss/Minecraft-Zmod/files/3964758/BlockExpSettings.zip)

**Comment by DatrixTHLK** [comment]
Thanks for fixing my mistakes, it always the simple things that are the hardest to find. xD
